apiVersion: v1
kind: Service
metadata:
  name: standalone
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: standalone

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysqldeploy
spec:
  selector:
    matchLabels:
      app: standalone
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: standalone
    spec:
      containers:
      - image: mysql/mysql-server:latest
        name: standalone
        env:

        - name: "MYSQL_USER"

          value: "kubernetes"

        - name: "MYSQL_PASSWORD"

          value: "kubernetes"

        - name: "MYSQL_DATABASE"

          value: "db1"

        - name: "MYSQL_ROOT_PASSWORD"

          value: "password"
        ports:
        - containerPort: 3306
          name: standalone
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim