apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdeploy2
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: varadjoshi89/backend:latest
        imagePullPolicy: Always
        name: backend
        ports:
          - containerPort: 8080


